services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: communication_backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: communication_frontend
    ports:
      - "3000:80"

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: communication_ai_service
    ports:
      - "8000:8000"